chapter19_part1: /210_Identifying_Words/20_Standard_tokenizer.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #129
Opened 2016-04-26 02:17 UTC by lxy4java

Thanks for the Pull Request!  We really appreciate your help and contribution!

Before you submit the PR, have you signed Contributor License Agreement: https://www.elastic.co/contributor-agreement/ ?

PR's (no matter how small) cannot be merged until the CLA has been signed.  
It only needs to be signed once, however. Thanks!

2016-05-01 01:59 UTC, medcl commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +分词器接受一个字符串作为输入，将((("words", "identifying", "using standard tokenizer")))((("standard tokenizer")))((("tokenizers")))这个字符串拆分成单独的词，或 _词汇单元_
词，或
中间的，多余了

2016-05-01 02:01 UTC, medcl commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`标准分词器` ((("Unicode Text Segmentation algorithm"))) 使用Unicode文本分割算法（定义在 http://unicode.org/reports/tr29/[Unicode Standard Annex #29]）来寻找单词间的界限，并且输出界限之间的任何东西。Unicode技术使其可以成功的分词包含混合语言的文本。
中文和英文之间要加空格，下同

2016-05-04 07:44 UTC, lxy4java commented
@medcl   谢谢 M大 已修改

2016-05-06 11:11 UTC, medcl commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +有趣的是词汇识别的算法。 `whitespace` （空格）分词器((("whitespace tokenizer")))仅仅按空格 -- 空白，tabs，换行符等等拆分 -- 想象下单个词汇单元的连续的无空格字符串。例如：
空白，tabs，换行符
中间用、吧

2016-05-20 07:32 UTC, lxy4java commented
@medcl   已修改。。谢谢 M 大。

2016-05-20 13:34 UTC, medcl commented
LGTM , commits squash成一个吧

2016-08-07 09:55 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +（也许可以描述成类似标点的符号），并且输出一个词汇单元流作为输出。
discarding 意为舍弃，(perhaps discarding some characters like punctuation)翻译为“可以舍弃一些标点符号”会不会更合适呢？ @lxy4java

2016-08-07 10:08 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +有趣的是词汇识别的算法。 `whitespace` （空格）分词器((("whitespace tokenizer")))仅仅按空格 -- 空白、tabs、换行符等等拆分 -- 想象下单个词汇单元的连续的无空格字符串。例如：
1. 建议去掉“仅仅”
2. “and assumes that contiguous nonwhitespace characters form a single token”
翻译为"令连续的非空格字符组成一个词汇单元"会不会更合适呢。

2016-08-07 11:02 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`标准分词器` ((("Unicode Text Segmentation algorithm"))) 使用 Unicode 文本分割算法（定义在 http://unicode.org/reports/tr29/[Unicode Standard Annex #29]）来寻找单词间的界限，并且输出界限之间的任何东西。 Unicode 技术使其可以成功的分词包含混合语言的文本。
1. "定义在" 换为 “定义来源于” 会否更通顺。
2. “任何东西”感觉有些不妥，翻译为输出界限之间的内容是否要稍微合适一些呢。
3. “可以成功的分词包含混合语言的文本“改为“可以成功的对包含混合语言的文本进行分词”，语序上会不会更合适一些呢

2016-08-07 11:04 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +标点符号可能是单词的一部分，也可能不是，这取决于它出现的位置：
此处译为“标点符号是否被认为是单词的一部分”是不是更合适一些呢

2016-08-07 11:08 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +在这个例子中，`You're` 中的撇号被视为单词的一部分，然而 `'favorite'` 中的单引号则不会被视为单词的一部分，所以分词结果如下： `You're` 、 `my` 、 `favorite` 。
此处的撇号与后文中的单引号，为避免误解，是否统一为单引号更好呢

2016-08-07 11:11 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`uax_url_email` （标准Email URL分词器）分词的方式和 `标准分词器` 一样。不过它只能识别email地址和URLs并且将这些输出为单个词汇单元。 `标准分词器` 则不一样，会将email地址和URLs拆分成独立的单词，例如，email地址 `joe-bloggs@foo-bar.com` 的分词结果为 `joe` 、 `bloggs` 、 `foo` 、 `bar.com
此处建议保留一份原文((("email addresses and URLs, tokenizer for")))吧

2016-08-07 11:23 UTC, gitqh commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`字符分词器` ，在另一方面，按照任何非字符进行拆分，这样的话将会返回((("letter tokenizer")))如下单词： `You` 、 `re` 、 `the` 、 `st` 、 `runner` 、 `home` 。
建议将((("letter tokenizer"))) 提到"这样的话"之后

2016-09-04 13:52 UTC, lxy4java commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +有趣的是词汇识别的算法。 `whitespace` （空格）分词器((("whitespace tokenizer")))仅仅按空格 -- 空白、tabs、换行符等等拆分 -- 想象下单个词汇单元的连续的无空格字符串。例如：
非常感谢！ 
assumes  我还是觉得翻译为想象下，这个词是假设的意思
连续的非空格字符组成一个词汇单元 
很赞

2016-09-04 13:56 UTC, lxy4java commented
@gitqh  已修改 谢谢~~

2016-11-22 13:39 UTC, node commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +（可以舍弃一些标点符号），并且输出一个词汇单元流。
优化成这样？

> （可能会丢弃一些标点符号等字符），然后输出一个_词汇单元流_。

2016-11-22 13:44 UTC, node commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +有趣的是词汇识别的算法。 `whitespace` （空格）分词器((("whitespace tokenizer")))按空格 -- 空白、tabs、换行符等等拆分 -- 想象下一个连续的非空格字符组成一个词汇单元。例如：
我个人理解这里的 breaks and assumes 是并列关系，所有后半句是否翻译为 假设xxxxxx 更合适？

2016-11-22 13:47 UTC, node commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`标准分词器` 是大多数语言分词的一个合理的起点，特别是西方语言。事实上，它是很多具体语言的分词器的基础，如 `英语` 、`法语` 、和 `西班牙语` 分析器。它也支持亚洲语言，只是有些缺陷，你可以考虑替换为 `icu_分词器` ，在 ICU 插件中可用。
建议：
> 它是很多特定语言分词器的基础

2016-12-07 06:43 UTC, candythinking commented on 210_Identifying_words/20_Standard_tokenizer.asciidoc
> +`标准分词器` 是大多数语言分词的一个合理的起点，特别是西方语言。事实上，它是很多具体语言的分词器的基础，如 `英语` 、`法语` 、和 `西班牙语` 分析器。它也支持亚洲语言，只是有些缺陷，你可以考虑替换为 `icu_分词器` ，在 ICU 插件中可用。
它是很多具体语言的分词器的基础 => 它形成了大多数语言特定分析器的基础

2016-12-07 06:46 UTC, candythinking requested changes
提了一点comment

2016-12-16 12:23 UTC, closed without merging