chapter44_part8: 410_Scaling/45_Index_per_timeframe.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #220
Opened 2016-08-25 01:48 UTC by biyuhao

2016-11-20 12:28 UTC, rockybean requested changes

2016-11-20 12:28 UTC, rockybean commented on 410_Scaling/45_Index_per_timeframe.asciidoc
> +https://www.elastic.co/guide/en/logstash/current/index.html[Logstash] 采集、解析日志并在将它们索引进Elasticsearch之前富集化。((("Logstash")))
采集、解析并在将日志写入 Elasticsearch 之前将格式优化

2016-11-20 12:28 UTC, rockybean commented on 410_Scaling/45_Index_per_timeframe.asciidoc
> +搜索引擎最传统的使用案例中包含一个增长缓慢相对稳定的文档集合。搜索查找最相关的文档，而不关心它是何时创建的。
搜索引擎中大多数传统使用场景都是增长缓慢且相对稳定的文档集合。

2016-11-20 12:28 UTC, rockybean commented on 410_Scaling/45_Index_per_timeframe.asciidoc
> +如果我们可能拥有一个这种文档类型的大索引，我们可能会很快用尽存储空间。日志事件会不断的进来，不会停顿也不会中断。
如果我们为此种类型的文档建立一个超大索引，我们会很快耗尽存储空间。

2016-11-20 12:28 UTC, rockybean commented on 410_Scaling/45_Index_per_timeframe.asciidoc
> +然而我们可以使用一个 _时间范围索引_((("indices", "index per-timeframe")))。你可以着手于一个按年的索引 (`logs_2014`) 或按月的索引 (`logs_2014-10`) 。
替代方案是，我们使用一个……

2016-12-03 11:12 UTC, medcl commented on 410_Scaling/45_Index_per_timeframe.asciidoc
> +==== 时间范围索引
时间范围索引
加个 按字
按时间范围索引
怎么样？
其他的 LGTM

2016-12-04 13:35 UTC, merged