chaper44_part9:/410_Scaling/50_Index_templates.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #221
Opened 2016-08-25 03:47 UTC by biyuhao

2016-11-20 12:35 UTC, rockybean requested changes

2016-11-20 12:35 UTC, rockybean commented on 410_Scaling/50_Index_templates.asciidoc
> +对于日志记录类应用，依赖于自动创建索引比手动创建要更加方便。
相比手动创建索引，依赖自动创建会更加方便。

2016-11-20 12:35 UTC, rockybean commented on 410_Scaling/50_Index_templates.asciidoc
> +通常我们想要控制一些新建索引的设置（settings）和映射（mappings）。也许我们想要限制分片数为 `1` ，并且禁用 `_all` 域。
括号中的内容有意义吗？

2016-12-03 08:51 UTC, biyuhao commented on 410_Scaling/50_Index_templates.asciidoc
> +通常我们想要控制一些新建索引的设置（settings）和映射（mappings）。也许我们想要限制分片数为 `1` ，并且禁用 `_all` 域。
我觉得这里加上可以便于理解避免歧义。

2016-12-04 02:42 UTC, rockybean commented on 410_Scaling/50_Index_templates.asciidoc
> +通常我们想要控制一些新建索引的设置（settings）和映射（mappings）。也许我们想要限制分片数为 `1` ，并且禁用 `_all` 域。
@medcl 这个问题你看下，是该怎么整

2016-12-30 09:09 UTC, medcl commented
LGTM

2016-12-30 09:10 UTC, merged