chapter44_part10:/410_Scaling/55_Retiring_data.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #243
Opened 2016-09-04 03:36 UTC by biyuhao

2016-11-20 12:43 UTC, rockybean requested changes

2016-11-20 12:43 UTC, rockybean commented on 410_Scaling/55_Retiring_data.asciidoc
> +Elasticsearch 是如何得知哪台是你最好的服务器呢？你可以通过给每台服务器指定任意的标签来告诉它。
指定自定义的标签
翻译成随意不好里接

2016-11-20 12:43 UTC, rockybean commented on 410_Scaling/55_Retiring_data.asciidoc
> +我们可以通过按如下设置（Settings）来创建今日的索引来确保它被分配到我们最好的服务器上：
括号里的内容有必要吗？

2016-11-20 12:43 UTC, rockybean commented on 410_Scaling/55_Retiring_data.asciidoc
> +在关闭之前，值得我们去刷写索引来确保没有事务残留在事务日志中。一个空白的事务日志会使得索引在重新打开时恢复得更快：
flush 翻译为 强制刷新 会更好一些

2016-12-04 02:41 UTC, rockybean commented
@biyuhao 其他的修改如果有意见的尽快给出反馈

2016-12-04 06:32 UTC, biyuhao commented on 410_Scaling/55_Retiring_data.asciidoc
> +Elasticsearch 是如何得知哪台是你最好的服务器呢？你可以通过给每台服务器指定任意的标签来告诉它。
原文用的arbitrary是“ arbitrary”
如果是“ arbitrary”应该会用custom
我觉得这样和原文更一致一些

2016-12-06 07:01 UTC, rockybean approved these changes

2016-12-30 09:06 UTC, merged