chapter44_part13:/410_Scaling/70_Faking_it.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #246
Opened 2016-09-05 03:42 UTC by biyuhao

2016-11-20 12:55 UTC, rockybean requested changes

2016-11-20 12:55 UTC, rockybean commented on 410_Scaling/70_Faking_it.asciidoc
> +为了保持我们的设计简洁优雅，我们想让我们的应用认为我们为每个用户都有一个专门的索引——或者按照我们的例子每个论坛一个——尽管实际上我们用的是一个大的<<shared-index,shared index>>。
为了保持设计的简洁，我们需要我们的应用认为我们为每个用户创建了一个特定的索引

2016-12-04 02:37 UTC, rockybean commented
LGTM

2016-12-13 13:54 UTC, luotitan commented on 410_Scaling/70_Faking_it.asciidoc
> +<1> 两个 `routing` 的值都会应用，返回对结果会匹配其中一个过滤器。
匹配任意一个过滤器。

2016-12-13 14:08 UTC, luotitan commented on 410_Scaling/70_Faking_it.asciidoc
> +对 `baking` 别名对查询只会在关联到自定义路由值的分片上执行，结果也已经自动地按照我们指定的过滤器过滤过了：
在 `baking`  别名上的查询只在自定义路由值关联的分片上运行，并且结果自动按照我们指定的过滤器进行了过滤：

2016-12-30 08:59 UTC, merged