chapter22_part7:/300_Aggregations/40_scope.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #261
Opened 2016-09-09 06:07 UTC by pengqiuyuan

初译

2016-12-01 08:29 UTC, qindongliang commented on 300_Aggregations/40_scope.asciidoc
> +聚合与搜索请求同时执行，但是我们需要理解一个新概念： _范围_ 。((("scoping aggregations", id="ix_scopeaggs", range="startofrange"))) 默认情况下，聚合与查询是对同一范围进行操作的，也就是说，聚合是基于我们查询匹配的文档集合进行计算的。
聚合与搜索请求同时执行
聚合可以与搜索请求同时执行

2016-12-01 08:29 UTC, qindongliang commented on 300_Aggregations/40_scope.asciidoc
> +我们可以看到聚合是隔离的。现实中，Elasticsearch 认为 `没有指定查询` 和 `查询所有文档` 是等价的。前面这个查询内部会翻译成：
内部会翻译成
内部会转化成下面的这个请求：

2016-12-05 01:16 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +所有聚集的例子到目前为止，你可能已经注意到，我们省略了一个 `query` 的搜索请求((("queries", "in aggregations")))((("aggregations", "scoping"))) 完整的请求只不过是一个聚合。
我们省略了一个 `query` 的搜索请求-->我们的搜索请求省略了一个 `query`

2016-12-05 01:22 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +让我们看看第一个聚合的示例：
第一个--》其中一个；不过这里好像不改也不影响

2016-12-05 01:30 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +一旦有了范围的概念，我们就能更进一步对聚合进行自定义。我们前面所有的示例都是对 _所有_ 数据计算统计信息的：销量最高好的汽车，所有汽车的平均售价，最佳销售月份等等。
销量最高好的汽车--》销量最高的汽车/销量最好的汽车

2016-12-05 01:36 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +加入一个搜索信息是无法将任何静态的仪表板变成一个实时数据展示仪的。((("dashboards", "adding a search bar"))) 这让用户可以搜索数据，查看所有实时更新的图形（由于聚合的支持以及对查询范围的限定）。
加入一个搜索信息是无法将任何静态的仪表板变成一个实时数据展示仪的--》加入一个搜索栏可以将任何静态的仪表板变成一个实时数据搜索设备；原文是can哦

2016-12-05 01:39 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +例如，比方说我们想知道福特汽车与 `所有` 汽车平均售价的比较。我们可以用普通的聚合（查询范围内的）得到第一个信息，然后用 `全局` ((("buckets", "global")))((("global bucket"))) 桶获得第二个信息。
`所有` --》 _所有_

2016-12-05 01:43 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +<1> 聚合操作在查询范围内（例如：所有文档匹配 `ford` ）
`ford` --》+ford+；仍然是可改可不改的

2016-12-05 01:45 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +如果能一直坚持读到这里，应该知道我们有个真言：尽可能的使用过滤器。它同样可以应用于聚合，在下一章中，我们会展示如何对聚合结果进行过滤而不是仅对查询范围做限定。((("scoping aggregations", range="endofrange", startref="ix_scopeaggs")))
这里的“真言”是不是“箴言”写错了？不是的话当我没说~

2016-12-05 02:44 UTC, AlixMu commented on 300_Aggregations/40_scope.asciidoc
> +所有聚集的例子到目前为止，你可能已经注意到，我们省略了一个 `query` 的搜索请求((("queries", "in aggregations")))((("aggregations", "scoping"))) 完整的请求只不过是一个聚合。
The entire request was simply an aggregation.
这里可不可以这样翻译（`query`后面少了一个标点符号，这里如果翻译成完整会有些歧义，The entire request应该是指之前省略 `query` 的聚合请求）：
所有聚集的例子到目前为止，你可能已经注意到，我们省略了一个 `query` 的搜索请求，整个请求只不过是一个聚合。

2016-12-05 06:45 UTC, pengqiuyuan commented on 300_Aggregations/40_scope.asciidoc
> +如果能一直坚持读到这里，应该知道我们有个真言：尽可能的使用过滤器。它同样可以应用于聚合，在下一章中，我们会展示如何对聚合结果进行过滤而不是仅对查询范围做限定。((("scoping aggregations", range="endofrange", startref="ix_scopeaggs")))
箴言\真言，应该都可以，我觉得。

2016-12-05 06:46 UTC, pengqiuyuan commented on 300_Aggregations/40_scope.asciidoc
> +如果能一直坚持读到这里，应该知道我们有个真言：尽可能的使用过滤器。它同样可以应用于聚合，在下一章中，我们会展示如何对聚合结果进行过滤而不是仅对查询范围做限定。((("scoping aggregations", range="endofrange", startref="ix_scopeaggs")))
![dee724b8-1c08-4b9b-bef3-41512c906e78](https://cloud.githubusercontent.com/assets/4953205/20875943/7f26e136-baf9-11e6-8321-531ce25fe0e6.png)
![14dd63fc-5eb0-4842-a214-c1a341123b91](https://cloud.githubusercontent.com/assets/4953205/20875950/8c71840e-baf9-11e6-8b44-c84334ba9768.png)

2016-12-05 06:47 UTC, tangmisi commented on 300_Aggregations/40_scope.asciidoc
> +如果能一直坚持读到这里，应该知道我们有个真言：尽可能的使用过滤器。它同样可以应用于聚合，在下一章中，我们会展示如何对聚合结果进行过滤而不是仅对查询范围做限定。((("scoping aggregations", range="endofrange", startref="ix_scopeaggs")))
ok

2016-12-05 06:48 UTC, tangmisi commented
你修改的时候顺便本地编译一下吧，我没把环境搭起来...

2016-12-05 06:50 UTC, pengqiuyuan commented
ok ，我提 pr 的时候编译过，修改的时候就没编译了，偷懒了哈哈

2016-12-05 09:24 UTC, biyuhao requested changes
几个小问题，希望再斟酌一下

2016-12-05 09:24 UTC, biyuhao commented on 300_Aggregations/40_scope.asciidoc
> +== 范围限定
Scoping Aggregations
“范围限定” -> “范围限定的聚合”
是不是感觉缺了点东西

2016-12-05 09:24 UTC, biyuhao commented on 300_Aggregations/40_scope.asciidoc
> +所有聚集的例子到目前为止，你可能已经注意到，我们的搜索请求省略了一个 `query` 。((("queries", "in aggregations")))((("aggregations", "scoping"))) 整个请求只不过是一个聚合。
“所有聚集” -> “所有聚合”
保持统一感觉要好一点

2016-12-05 09:24 UTC, biyuhao commented on 300_Aggregations/40_scope.asciidoc
> +我们可以看到聚合是隔离的。现实中，Elasticsearch 认为 `没有指定查询` 和 `查询所有文档` 是等价的。前面这个查询内部会转化成下面的这个请求：
没有指定查询 和 查询所有文档
原文使用的是`"`这个语法

2016-12-06 06:11 UTC, biyuhao approved these changes

2016-12-06 06:18 UTC, biyuhao commented
LGTM.

2016-12-09 00:30 UTC, merged