chapter22_part8:/300_Aggregations/45_filtering.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #262
Opened 2016-09-09 07:34 UTC by pengqiuyuan

初译

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
> +== 信息聚合之聚合过滤
过滤和聚合

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
> +=== 查询（Filtered Query）
过滤

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
> +这正如我们在前面章节中讨论过那样，从根本上讲，使用 `non-scoring` 查询和使用 `match` 查询没有任何区别。查询（包括了一个过滤器）返回一组文档的子集，聚合正是操作这些文档。它只是碰巧省略 `scoring` ，并可能主动缓存 `bitsets` 等。
它只是碰巧省略 `scoring` ，并可能主动缓存 `bitsets` 等。
使用filter query会忽略评分，并有可能会缓存结果数据等等

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
> +=== 展示过滤器（Post Filter）
后过滤器

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
> +我们可能会想，"有 _只_ 对搜索结果进行过滤而不过滤聚合结果的方式吗？"((("filtering", "search results, not the aggregation")))((("post filter"))) 答案是使用 `post_filter` 。
"有 _只_ 对搜索结果进行过滤而不过滤聚合结果的方式吗？
有没有一种方式在没有聚合操作的时候，仅仅是对一次搜索后的结果进行二次过滤呢？

2016-11-30 10:06 UTC, qindongliang commented on 300_Aggregations/45_filtering.asciidoc
>  ====
当你过滤不同的过滤结果集在聚合中，你才应该使用post_filter。

2016-12-05 01:50 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +这正如我们在前面章节中讨论过那样，从根本上讲，使用 `non-scoring` 查询和使用 `match` 查询没有任何区别。查询（包括了一个过滤器）返回一组文档的子集，聚合正是操作这些文档。使用 `filter query` 会忽略评分，并有可能会缓存结果数据等等。
`non-scoring`-->non-scoring；木有太大关系

2016-12-05 01:53 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +这正如我们在前面章节中讨论过那样，从根本上讲，使用 `non-scoring` 查询和使用 `match` 查询没有任何区别。查询（包括了一个过滤器）返回一组文档的子集，聚合正是操作这些文档。使用 `filter query` 会忽略评分，并有可能会缓存结果数据等等。
`filter query` 这个在原文好像也木有诶，难道我们看的不是同一个版本的文档？如果真的要用，用filtered query好像比较好

2016-12-05 02:01 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +但是如果我们只想对聚合结果过滤怎么办？((("filtering", "aggregation results, not the query")))((("aggregations", "filtering just aggregations"))) 假设我们正在创建一个可以搜索汽车经销商的页面，
假设我们正在创建一个可以搜索汽车经销商的页面 是不是 改为 假设我们正在为汽车经销商创建一个搜索页面 比较好，for有 为了 的意思，如果是 搜索汽车经销商的页面 ，是否用of比较贴切。。而且汽车信息也不止汽车经销商的内容；不过好像这个搜索页面不止是经销商可以利用，普通民众也可以利用，这里说为经销商创建页面又好像有点奇怪了~

2016-12-05 02:07 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +<2> `avg` 度量只会对 +ford+ 和一月以内售出的文档计算平均售价。
一月以内--》上个月

2016-12-05 02:10 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +目前为止，我们可以同时对搜索结果和聚合结果进行过滤（ `non-scoring` 的 `filter` 查询），以及针对聚合结果的一部分进行过滤（ `filter` 桶）。
`non-scoring`--》不计算得分的；而且原文没有“``"呢

2016-12-05 02:14 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +我们可能会想，"有没有一种方式在没有聚合操作的时候，仅仅是对一次搜索后的结果进行二次过滤呢？"((("filtering", "search results, not the aggregation")))((("post filter"))) 答案是使用 `post_filter` 。
在没有聚合操作的时候，仅仅是对一次搜索后的结果进行二次过滤呢--> _只_ 过滤搜索结果，不过滤聚合结果呢

2016-12-05 02:25 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +它是顶层搜索请求元素接收一个过滤器。这个过滤器在查询 _之后_ 执行（这正是该过滤器的名字的由来：它在查询之后 +post+ 执行）。正因为它在查询之后执行，它对查询范围没有任何影响，所以对聚合也不会有任何影响。
它是顶层搜索请求元素接收一个过滤器--》它是接收一个过滤器的顶层搜索请求元素

2016-12-05 02:54 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +当你过滤不同的过滤结果集在聚合中，你才应该使用 `post_filter` ，((("post filter", "performance and"))) 有时用户会在普通搜索使用 `post_filter` 。
当你过滤不同的过滤结果集在聚合中--》当你需要对搜索结果和聚合结果做不同的过滤时

2016-12-05 02:55 UTC, tangmisi commented on 300_Aggregations/45_filtering.asciidoc
> +不要这么做！ `post_filter` 的特性是在查询 _之后_ 执行，所以任何过滤所带来的好处（比如缓存）都会完全失去。
任何过滤所带来的好处--》任何过滤对性能带来的好处；这里好像不改也行

2016-12-05 06:16 UTC, pengqiuyuan commented on 300_Aggregations/45_filtering.asciidoc
> +这正如我们在前面章节中讨论过那样，从根本上讲，使用 `non-scoring` 查询和使用 `match` 查询没有任何区别。查询（包括了一个过滤器）返回一组文档的子集，聚合正是操作这些文档。使用 `filter query` 会忽略评分，并有可能会缓存结果数据等等。
It just happens to omit scoring .. It 这里指的是 `non-scoring`  或者 `filtering` query
这里可以修改为 `filtering` query
[When used in filtering context, the query is said to be a "non-scoring" or "filtering" query. ](https://www.elastic.co/guide/en/elasticsearch/guide/current/_finding_exact_values.html)

2016-12-05 06:42 UTC, tangmisi commented
LGTM

2016-12-05 09:01 UTC, biyuhao requested changes
小部分小改，格式问题修改

2016-12-05 09:01 UTC, biyuhao commented on 300_Aggregations/45_filtering.asciidoc
这里的空行必须要删除，否则格式会有问题，
可以对比原版的格式会发现有不同
1.最后一句多出一个框 2.post_filter的格式没了

2016-12-05 09:01 UTC, biyuhao commented on 300_Aggregations/45_filtering.asciidoc
> +这里我们无法简单的做范围限定，因为有两个不同的条件。搜索结果必须是 +ford+ ，但是聚合结果必须满足 +ford+
这里的 AND 我认为是Lucene的查询语法，
我觉得应该保持原样就好

2016-12-06 06:33 UTC, biyuhao commented on 300_Aggregations/45_filtering.asciidoc
> +如果我们想找到售价在 $10，000 美元之上的所有汽车同时也为这些车计算平均售价，((("filtering", "serch query results")))((("filtering query")))
`$10，000` 这里的逗号貌似应该用英文的逗号，不好意思才看到
其他的都OK

2016-12-06 07:09 UTC, biyuhao approved these changes

2016-12-06 07:10 UTC, biyuhao commented
LGTM.

2016-12-09 00:31 UTC, merged