chapter22_part10:/300_Aggregations/55_approx_intro.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #266
Opened 2016-09-09 08:58 UTC by pengqiuyuan

初译

2016-10-06 17:36 UTC, Lywangwenbin commented
@pengqiuyuan 
在本地Mac上 出现格式错误 无法生成正常的html预览文本

2016-10-09 02:23 UTC, pengqiuyuan commented
编译错误的问题已解决 @Lywangwenbin <https://github.com/Lywangwenbin>


2016-10-07 1:36 GMT+08:00 wwb-et <notifications@github.com>:

> @pengqiuyuan <https://github.com/pengqiuyuan>
> 在本地Mac上 出现格式错误 无法生成正常的html预览文本
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/elasticsearch-cn/elasticsearch-definitive-guide/pull/266#issuecomment-252034339>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AEuUdV8uXk0cv1XbVHSasoZ2sFpwEHHGks5qxTGQgaJpZM4J41qw>
> .
>

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +=== 查找唯一值的数目（Finding Distinct Counts）
统计去重后的数量

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +Distinct 计数是一个普通的操作，可以回答很多基本的商业问题：
+Distinct 计数是一个普通的操作
去重是一个很常见的操作

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +- 对于低基数集能够达到高准确度。
对于低基数集能够达到高准确度。
小的数据集精度是非常高的

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +- 固定的内存使用。即使有几千或甚至上百亿的唯一值，内存的使用也只是依赖于配置里的精度要求。
我们可以通过配置参数，来设置去重需要使用的固定内存量，这一点数据集的大小无关。

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +基本上说，预先计算并不能保证所有的字段都快，它只对那些具有高基数和内容很长的字符串字段有作用。需要记住的是预先计算也只是简单地将代价转到索引时，代价就在那里，不增不减。
需要记住的是预先计算也只是简单地将代价转到索引时，代价就在那里，不增不减。
记住，预计算只是简单的将查询时消耗的时间给提前转移到索引时的时候，并非没有任何代价，区别在于你可以选择在什么时候做这件事要么在索引时要么在查询时

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +现在 `cardinality` 度量会读取 `"color.hash"` 里的值（预先计算的哈希值），并将它们作为原始值的动态哈希值。
并将它们作为原始值的动态哈希值。
并替代动态hash值，直接使用已经算好的hash值

2016-11-29 10:00 UTC, qindongliang commented on 300_Aggregations/60_cardinality.asciidoc
> +每个文档节省的时间有限，但如果哈希每个字段需要 10 纳秒而我们的聚合需要访问一亿文档，那么每个查询就需要多花 1 秒钟的时间。如果我们发现自己在很多文档都会使用 `cardinality` 基数，可以做些性能分析看是否有必要在我们部署的应用中采用预先计算哈希的方式。
每个文档节省的时间有限，但如果哈希每个字段需要 10 纳秒而我们的聚合需要访问一亿文档，那么每个查询就需要多花 1 秒钟的时间。如果我们发现自己在很多文档都会使用 `cardinality` 基数，可以做些性能分析看是否有必要在我们部署的应用中采用预先计算哈希的方式。

单个文档节省的时间是非常少的，但是如果你聚合100万数据，每条数据花费10纳秒的时间，那么在每次查询时都会额外增加1秒，如果我们要在非常大量的数据里面使用去重，我们可以权衡使用预计算的意义，是否需要提前计算hash，从而在查询时获得更好的性能。

2016-11-29 10:14 UTC, pengqiuyuan commented on 300_Aggregations/60_cardinality.asciidoc
> +每个文档节省的时间有限，但如果哈希每个字段需要 10 纳秒而我们的聚合需要访问一亿文档，那么每个查询就需要多花 1 秒钟的时间。如果我们发现自己在很多文档都会使用 `cardinality` 基数，可以做些性能分析看是否有必要在我们部署的应用中采用预先计算哈希的方式。
100 million 是 一亿

2016-12-05 03:42 UTC, tangmisi commented on 300_Aggregations/60_cardinality.asciidoc
> +- 每月有多少独立用户购买了商品？
此处的“独立”感觉有点奇怪，然而想不到什么词可以形容unique。。。

2016-12-05 03:54 UTC, tangmisi commented on 300_Aggregations/60_cardinality.asciidoc
> +因为 HLL 只需要字段内容的哈希值，我们可以在索引时就预先计算好。((("hashes, pre-computing for cardinality metric"))) 就能在查询时跳过哈希计算然后将数据信息直接加载出来。
将数据信息直接加载出来--》将哈希值从fielddata直接加载出来；强迫症觉得这样表述比较准确而已，也可以不改~

2016-12-05 03:55 UTC, tangmisi commented on 300_Aggregations/60_cardinality.asciidoc
> +基本上说，预先计算并不能保证所有的字段都快，它只对那些具有高基数和内容很长的字符串字段有作用。需要记住的是，预计算只是简单的将查询消耗的时间提前转移到索引时，并非没有任何代价，区别在于你可以选择在什么时候做这件事，要么在索引时，要么在查询时。
所有的字段都快--》所有的字段都更快

2016-12-05 04:03 UTC, tangmisi commented on 300_Aggregations/60_cardinality.asciidoc
> +单个文档节省的时间是非常少的，但是如果你聚合一亿数据，每条数据花费 10 纳秒的时间，那么在每次查询时都会额外增加 1 秒，如果我们要在非常大量的数据里面使用去重，我们可以权衡使用预计算的意义，是否需要提前计算 hash，从而在查询时获得更好的性能。
最后一句感觉跟原文描述挺不一样了，不过不管了...是否把 “去重” 改为 “ `cardinality` ”？不改也可以...

2016-12-05 04:46 UTC, pengqiuyuan commented on 300_Aggregations/60_cardinality.asciidoc
> +- 每月有多少独立用户购买了商品？
网站独立访客，UV是unique visitor的简写
这里要是写 UV 就不奇怪了😊，或者网站独立访客。
改为
网站独立访客是多少？

2016-12-05 04:58 UTC, tangmisi commented on 300_Aggregations/60_cardinality.asciidoc
> +- 每月有多少独立用户购买了商品？
噢，原来如此，那是我见得少了~（大拇指）

2016-12-05 04:59 UTC, tangmisi commented
LGTM

2016-12-05 12:37 UTC, biyuhao requested changes
“阀值” -> “阈值”，
其他少量部分内容可斟酌调整

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +((("unique counts"))) 可能会对 SQL 形式比较熟悉：
"可能会对" -> "你可能会对"
这样更通顺些

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +去重是一个很常见的操作，可以回答很多基本的商业问题：
“商业问题” -> “业务问题”
我觉得这样稍微好一点

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +我们可以用 `cardinality` 度量确定经销商销售汽车颜色的种类：
“汽车颜色的种类” -> “汽车颜色的数量”
原文这里是```the number of car colors```

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +- 我们可以通过配置参数，来设置去重需要使用的固定内存量，这一点与数据集的大小无关。
这句我认为可以翻译为：
- 固定的内存使用量。无论数千还是数十亿的唯一值，内存使用量只与你配置的精确度相关。

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +这个阀值定义了在何种基数水平下我们希望得到一个近乎精确的结果。参考以下示例：
"阀值" -> "阈值"

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +<1> `precision_threshold` 接受 0–40，000 之间的数字，更大的值还是会被当作 40，000 来处理。
“40，000” -> “40,000”
这里应当使用英文逗号

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +示例会确保当字段唯一值在 100 以内时会得到非常准确的结果。尽管算法是无法保证这点的，但如果基数在阀值以下，几乎总是 100% 正确的。高于阀值的基数会开始节省内存而牺牲准确度，同时也会对度量结果带入误差。
“阀值” -> “阈值”

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +对于指定的阀值，HLL 的数据结构会大概使用内存 `precision_threshold * 8` 字节，所以就必须在牺牲内存和获得额外的准确度间做平衡。
“阀值” -> “阈值”， 下同

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +对于指定的阀值，HLL 的数据结构会大概使用内存 `precision_threshold * 8` 字节，所以就必须在牺牲内存和获得额外的准确度间做平衡。
如果改为 “使用......字节的内存” 感觉要更通顺点

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +如果想要获得唯一数目的值， _通常_ 需要查询整个数据集合（或几乎所有数据）。((("cardinality", "optimizing for speed")))((("distinct counts", "optimizing for speed"))) 所有基于所有数据的操作都必须迅速，原因是显然的。
“如果想要获得唯一数目的值” -> “如果想要获得唯一值的数目”
这样会不会更好一点

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +基本上说，预先计算并不能保证所有的字段都更快，它只对那些具有高基数和内容很长的字符串字段有作用。需要记住的是，预计算只是简单的将查询消耗的时间提前转移到索引时，并非没有任何代价，区别在于你可以选择在什么时候做这件事，要么在索引时，要么在查询时。
原文这里是 “and/or”
也就是 和/或者

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +基本上说，预先计算并不能保证所有的字段都更快，它只对那些具有高基数和内容很长的字符串字段有作用。需要记住的是，预计算只是简单的将查询消耗的时间提前转移到索引时，并非没有任何代价，区别在于你可以选择在什么时候做这件事，要么在索引时，要么在查询时。
原文的 ` _when_ ` 这里有一个语法

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +现在 `cardinality` 度量会读取 `"color.hash"` 里的值（预先计算的哈希值），并替代动态 hash 值，直接使用已经算好的 hash 值。
`并替代动态 hash 值，直接使用已经算好的 hash 值。` 
->
`取代动态计算原始值的哈希`
这样呢

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +单个文档节省的时间是非常少的，但是如果你聚合一亿数据，每条数据花费 10 纳秒的时间，那么在每次查询时都会额外增加 1 秒，如果我们要在非常大量的数据里面使用 `cardinality` ，我们可以权衡使用预计算的意义，是否需要提前计算 hash，从而在查询时获得更好的性能。
`每条数据花费 10 纳秒的时间` ->
`每个字段多花费 10 纳秒的时间`

2016-12-05 12:37 UTC, biyuhao commented on 300_Aggregations/60_cardinality.asciidoc
> +单个文档节省的时间是非常少的，但是如果你聚合一亿数据，每条数据花费 10 纳秒的时间，那么在每次查询时都会额外增加 1 秒，如果我们要在非常大量的数据里面使用 `cardinality` ，我们可以权衡使用预计算的意义，是否需要提前计算 hash，从而在查询时获得更好的性能。
文末一句：
做一些性能测试来检验预计算哈希是否适用于你的应用场景。
这样感觉会不会好一些

2016-12-06 07:08 UTC, biyuhao approved these changes

2016-12-06 07:09 UTC, biyuhao commented
LGTM.

2016-12-09 00:31 UTC, merged