chapter2_part9:/02_Dealing_with_language.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #391
Opened 2016-12-04 12:24 UTC by lephix

2016-12-06 03:40 UTC, biyuhao requested changes
基础格式调整，少量细节调整

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +如果文档确实包含用户查询的内容，那么这些文档应当出现在返回结果的最前面，而匹配程度较低的文档将会排在靠后的位置。
原文的`_do_` 这里有一个语法
`_确实_`

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +如果文档确实包含用户查询的内容，那么这些文档应当出现在返回结果的最前面，而匹配程度较低的文档将会排在靠后的位置。
`而匹配程度较低的文档将会排在靠后的位置。`
原文这里用的是`can be `
我认为可以改为 `较低的文档可以排在` 略有不同

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +以下列出了一些((("full text search", "finding inexact matches")))可优化的地方：
这里可以把`((("full text search", "finding inexact matches")))`
移到行尾，不然会在中间多出一个空格

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +*   通过提取单词的词干，清除单数和复数之间的差异&#x2014;`fox` 与 `foxes`&#x2014;以及时态上的差异&#x2014;`jumping` 、 `jumped` 与 `jumps`。请见 <<stemming>>。
```
与 `jumps`。
```
在这里需要再句号前面添加一个空格，不然解析的格式会有问题

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +*   清除常用词或者停用词，如 `the` ， `and` ， 和 `or` ，从而提升搜索性能。请见 <<stopwords>>。
`_stopwords_`
停用词这里有一个语法
`_停用词_`

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +*   清除类似 +´+, `^`, 和 `¨` 的变音符号，这样在搜索 `rôle` 的时候也会匹配 `role` ，反之亦然。请见 <<token-normalization>>。
```
+´+, `^`, 和 `¨`
```
这里分割的逗号应替换为中文逗号，另外`和`字前面的逗号我认为应该去掉，下同

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +*   检查拼写错误和其它拼写方式，或者同音异型词&#x2014;发音一致的不同单词，例如 `their` 与 `there` ， `meat` 、 `meet` 与 `mete` 。 请见 <<fuzzy-matching>>。
`其它拼写方式` -> `替代拼写方式` 或者`等价拼写方式` 这样呢

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +*   检查拼写错误和其它拼写方式，或者同音异型词&#x2014;发音一致的不同单词，例如 `their` 与 `there` ， `meat` 、 `meet` 与 `mete` 。 请见 <<fuzzy-matching>>。
`_homophones_` 这里有一个语法
`_同音异形异义词_` 或者 `_同音异义词_`

2016-12-06 03:40 UTC, biyuhao commented on 02_Dealing_with_language.asciidoc
> +在这之前，让我们看看如何更快更简单的开始。
`如何更快更简单的开始。` -> `如何更快更简单地开始。`

2016-12-06 05:07 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +如果文档确实包含用户查询的内容，那么这些文档应当出现在返回结果的最前面，而匹配程度较低的文档将会排在靠后的位置。
修改为 _确实_

2016-12-06 05:09 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +如果文档确实包含用户查询的内容，那么这些文档应当出现在返回结果的最前面，而匹配程度较低的文档将会排在靠后的位置。
> 我认为可以改为 较低的文档可以排在 略有不同
如果用可以的话，感觉会有点歧义。

2016-12-06 05:09 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +以下列出了一些((("full text search", "finding inexact matches")))可优化的地方：
按建议修改

2016-12-06 05:10 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +*   清除类似 +´+, `^`, 和 `¨` 的变音符号，这样在搜索 `rôle` 的时候也会匹配 `role` ，反之亦然。请见 <<token-normalization>>。
按照建议修改

2016-12-06 05:11 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +*   清除常用词或者停用词，如 `the` ， `and` ， 和 `or` ，从而提升搜索性能。请见 <<stopwords>>。
按照建议修改

2016-12-06 05:12 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +在这之前，让我们看看如何更快更简单的开始。
按照建议修改

2016-12-06 05:12 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +*   检查拼写错误和其它拼写方式，或者同音异型词&#x2014;发音一致的不同单词，例如 `their` 与 `there` ， `meat` 、 `meet` 与 `mete` 。 请见 <<fuzzy-matching>>。
按照建议修改

2016-12-06 05:13 UTC, lephix commented on 02_Dealing_with_language.asciidoc
> +*   通过提取单词的词干，清除单数和复数之间的差异&#x2014;`fox` 与 `foxes`&#x2014;以及时态上的差异&#x2014;`jumping` 、 `jumped` 与 `jumps`。请见 <<stemming>>。
按照建议修改

2016-12-06 06:03 UTC, biyuhao commented
LGTM.

2016-12-06 06:03 UTC, biyuhao approved these changes

2016-12-07 07:04 UTC, node commented on 02_Dealing_with_language.asciidoc
> +``我认识这句话里的所有单词，但是我不能理解它。''
这句还可以再改进下：

> 我认识这句话里的所有单词，但并不能理解全句。

2016-12-09 05:15 UTC, merged

2016-12-09 05:17 UTC, node reviewed
优化建议保留，先merge。

2016-12-09 05:17 UTC, node commented on 02_Dealing_with_language.asciidoc
> +    <p>我认识这句话里的所有单词，但并不能理解全句。</p>
这里考虑了一下，跟 @medcl 讨论，引用的名人名言原文可以不翻译（特别是上面一句已经翻译了，这里建议保留原文）。