chapter/chapter11_part6:/075_Inside_a_shard/60_Segment_merging.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #399
Opened 2016-12-07 02:08 UTC by tangmisi

2016-12-07 02:08 UTC, tangmisi commented
ref #170

2016-12-07 02:29 UTC, candythinking commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +每一个段都会消耗文件句柄、内存和cpu运行周期。更重要的是，每一次请求都需要检查每一个段的返回结果；段越多，搜索也就越慢。
根据英文里的 `in turn` 是轮流的意思，所以觉得翻译如下会不会好点
每一次请求都需要检查每一个段的返回结果 =>每个搜索请求都必须轮流检查每个段；所以段越多，搜索也就越慢。

2016-12-07 02:43 UTC, candythinking commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +这也是被删除的旧文档从文件系统中被清除的时刻。((("deleted documents", "purging of")))被删除的文档（或被更新文档的旧版本）不会被拷贝到新的大段中。
这也是被删除的旧文档从文件系统中被清除的时刻。((("deleted documents", "purging of"))) => 段合并的时候会将那些旧的已删除文档((("deleted documents", "purging of")))从文件系统中清除。

2016-12-07 02:55 UTC, candythinking commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +1. 当索引的时候，刷新（refresh）进程创建新的段，而且为搜索打开它们。
刷新（refresh）进程创建新的段，而且为搜索打开它们。 =>  refresh 操作会创建新的段并将段打开以供搜索使用。

2016-12-07 03:05 UTC, candythinking commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +    ** 一个包含新的段并且不包含旧的段和更小的段的新的提交点被写入。
改成以下会不会好点
一个包含新的段并且不包含旧的段和更小的段的新的提交点被写入。=》  写入一个包含新段的新提交点，但排除旧的和较小的段。

2016-12-07 06:07 UTC, candythinking requested changes
提交了几个comment

2016-12-08 08:10 UTC, AlixMu commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +    ** 一个包含新的段并且不包含旧的段和更小的段的新的提交点被写入。写入一个包含新段且排除旧的和较小的段的新提交点。
A new commit point is written that includes the new segment and excludes the old, smaller segments.
这句话翻译了两遍
一个包含新的段并且不包含旧的段和更小的段的新的提交点被写入。写入一个包含新段且排除旧的和较小的段的新提交点。
后者+1

2016-12-08 08:10 UTC, AlixMu commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +WARNING: `optimize` API _不应该_ 被用在一个动态索引--一个正在被活跃更新的索引。后台合并流程已经可以很好地完成工作。
WARNING: `optimize` API _不应该_ 被用在一个动态索引--一个正在被活跃更新的索引。
这里的符号是英文 -- ：
可不可以这样改动
WARNING: `optimize` API _不应该_ 被用在一个动态索引——一个正在被活跃更新的索引。

2016-12-08 08:10 UTC, AlixMu commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +请注意，使用 `optimize` API 触发段合并的话没有任何资源上的限制。这可能会消耗掉你节点上全部的I/O资源, 使其没有余裕来处理搜索请求，从而有可能使集群失去响应。
Be aware that merges triggered by the `optimize` API are not throttled at all.
这里可不可以这样翻译：
请注意，使用 `optimize` API 触发段合并的操作一点也不会受到任何资源上的限制。

2016-12-08 08:10 UTC, AlixMu commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
> +请注意，使用 `optimize` API 触发段合并的话没有任何资源上的限制。这可能会消耗掉你节点上全部的I/O资源, 使其没有余裕来处理搜索请求，从而有可能使集群失去响应。
Be aware that merges triggered by the `optimize` API are not throttled at all.
这里可不可以这样翻译（not...at all 翻译成 `一点也不` ，语气是不是会更加强烈）：
请注意，使用 `optimize` API 触发段合并的操作一点也不会受到任何资源上的限制。

2016-12-08 08:51 UTC, AlixMu commented
LGTM

2016-12-21 04:53 UTC, medcl commented on 075_Inside_a_shard/60_Segment_merging.asciidoc
>  image::images/elas_1110.png["Two commited segments and one uncommited segment in the process of being merged into a bigger segment"]
[]里面的是注释图片的,需要翻译,下同

2016-12-21 04:54 UTC, medcl commented
编译的时候有警告

Building HTML from elasticsearch-definitive-guide/book.asciidoc
asciidoc: WARNING: 60_Segment_merging.asciidoc: line 22: list item index: expected 1 got 3 at lib/ES/Util.pm line 68.

2016-12-30 07:56 UTC, medcl commented
@tangmisi   有空尽快处理一下么，谢谢

2017-01-04 06:25 UTC, merged