chapter3_part12:/030_Data/55_Bulk.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #411
Opened 2016-12-08 14:38 UTC by luotitan

在wharstr9027版本上重新提交。代价较小的批量操作

2016-12-09 02:24 UTC, AlixMu reviewed
LGTM

2016-12-09 07:55 UTC, biyuhao requested changes

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +如果不指定 `_id`，将会自动生成一个 ID ：
```
`_id`，
```
这里需要在逗号前添加一个空格

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +如果所有的请求都失败了，最顶层的 `error` 标志被设置为 `true` ，并且在相应的请求报告出错误明细：
如果所有的请求都失败了 ->
如果其中任何子请求失败

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +* 该行不能包含转义换行符，因为他们将会对解析造成干扰。这意味着这个 JSON _不_ 能使用 pretty 参数打印。
`不能包含转义换行符` ->
`不能包含未转义的换行符`

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +为了把所有的操作放在一起，一个完整的 `bulk` 请求 ((("bulk API", "common bulk request, example")))有以下形式:
`为了把所有的操作放在一起` ->
`把所有这些何合在一起`

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +这也意味着((("bulk API", "bulk requests, not transactions")))这个 `bulk` 请求不是原子的： 它不能实现事务控制。每个请求是单独处理的，因此一个请求的成功或失败不会影响其他的请求。
`这个 `bulk` 请求不是原子的`
可以去掉`这个`

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +这也意味着((("bulk API", "bulk requests, not transactions")))这个 `bulk` 请求不是原子的： 它不能实现事务控制。每个请求是单独处理的，因此一个请求的成功或失败不会影响其他的请求。
`它不能实现事务控制` ->
`不能用它来实现事物`

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +[[_Dont_Repeat_Yourself]]
`[[_Dont_Repeat_Yourself]]`
我在原文好像没发现有这一行

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +你仍然可以覆盖元数据行中的 `_index` 和 `_type` , 但是它将使用 URL 中的这些元数据值作为默认值：
```
你仍然可以覆盖元数据行中的 `_index` 和 `_type`
```
->
```
你仍然可以在元数据行中覆盖 `_index` 和 `_type` ，
```

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +[[_How_Big_Is_Too_Big]]
`[[_How_Big_Is_Too_Big]]`
同样，原文中这一行也没看到有

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +但是最佳值不是一个固定的值。它依赖于硬件、文档的大小和复杂度、索引和搜索的负载的整体情况。
`它依赖于` ->
`它完全取决于`

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +一个好的批量大小在开始处理后所占用的物理大小约为 5-15 MB。
一开始你可以尝试将批量请求的大小设置在 5-15 MB。

2016-12-09 07:55 UTC, biyuhao commented on 030_Data/55_Bulk.asciidoc
> +当性能开始下降，那么你的批量大小就太大了。一个好的办法是 1,000 到 5,000 个文档作为一个批次, 或者如果你的文档非常大，那么就要减少成批的文档个数。
期初，你可以将批量请求大小设置在 1,000 到 5,000 个文档，如果你的文档非常大，可能还要将这个值设置的更小。

2016-12-13 14:54 UTC, luotitan commented on 030_Data/55_Bulk.asciidoc
> +[[_Dont_Repeat_Yourself]]
这个是需要自己增加的，很多pr都需要补充这个，可以检查下自己的pr。

2016-12-13 14:56 UTC, luotitan commented on 030_Data/55_Bulk.asciidoc
> +一个好的批量大小在开始处理后所占用的物理大小约为 5-15 MB。
这个翻译有歧义，看看有没有更好的建议。

2016-12-21 04:46 UTC, medcl commented on 030_Data/55_Bulk.asciidoc
> +[[_Dont_Repeat_Yourself]]
参照https://www.elastic.co/guide/en/elasticsearch/guide/2.x/bulk.html#_don_8217_t_repeat_yourself
要小写吧

2016-12-21 13:57 UTC, biyuhao approved these changes

2016-12-30 07:53 UTC, merged