300_Aggregations/93_technical_docvalues.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #455
Opened 2017-01-19 13:56 UTC by medcl

2017-01-24 12:57 UTC, rockybean requested changes

2017-01-24 12:57 UTC, rockybean commented on 300_Aggregations/93_technical_docvalues.asciidoc
> +如果这些数据结构是纯粹的在内存中，那么唯一的选项只能是随着内存溢出（OutOfMemory）而崩溃（或是实现一个分页模式，正如操作系统的那样）。
如果这些数据结构是纯粹存储在 JVM 堆内存中的，那么唯一的结果只能是由于内存不足的异常而导致服务崩溃。

2017-01-24 23:55 UTC, medcl commented on 300_Aggregations/93_technical_docvalues.asciidoc
> +如果这些数据结构是纯粹的在内存中，那么唯一的选项只能是随着内存溢出（OutOfMemory）而崩溃（或是实现一个分页模式，正如操作系统的那样）。
可以把内存缓存 jvm 堆内存，其他的应该问题不大

2017-01-25 01:25 UTC, rockybean approved these changes

2017-01-25 01:26 UTC, rockybean commented
LGTM

2017-01-25 03:03 UTC, merged