230_Stemming/40_Choosing_a_stemmer.asciidoc
elasticsearch-cn/elasticsearch-definitive-guide pull request #457
Opened 2017-01-24 12:08 UTC by medcl

230_Stemming/40_Choosing_a_stemmer.asciidoc

2017-01-24 13:03 UTC, rockybean requested changes

2017-01-24 13:03 UTC, rockybean commented on 230_Stemming/40_Choosing_a_stemmer.asciidoc
> +关于那个是最好的词干提取器，不存在一个唯一的正确答案 -- 它要看你具体的需求。
关于哪个是

2017-01-24 13:03 UTC, rockybean commented on 230_Stemming/40_Choosing_a_stemmer.asciidoc
> +一个只有 10，000 个产品的小集合，你可能要更激进的提干来确保至少匹配到一些文档。
这里的逗号应该用英文的吧
10,000

2017-01-24 23:52 UTC, medcl commented
@rockybean 已修改

2017-01-25 01:26 UTC, rockybean approved these changes

2017-01-25 01:26 UTC, rockybean commented
LGTM

2017-01-25 03:00 UTC, merged